version: '2'

services:
  kafka:
    build:
      context: .
      args:
        KAFKA_VERSION: "${KAFKA_VERSION}"
  zookeeper:
    image: docker_kafka
    ports:
      - "2181:2181"
    container_name: zookeeper
    command: run zookeeper

