#!/bin/sh -eu

THIS=$0

CUR_DIR=`pwd`
cd `dirname $THIS`
TARGET_FILE=`basename $THIS`
while [ -L "$TARGET_FILE" ]; do
    TARGET_FILE=`readlink $TARGET_FILE`
    cd `dirname $TARGET_FILE`
    TARGET_FILE=`basename $TARGET_FILE`
done
BINDIR=`pwd -P`
export NIF_BIN_DIR=$BINDIR
cd "$CUR_DIR"

ERTS_DIR=`find $BINDIR/.. -maxdepth 1 -type d -name 'erts-*' -print -quit`

export NIF_BIN_DIR=$BINDIR

if [ -d  "$ERTS_DIR" ]; then
  # this is a release, try to use erts in release
  exec $ERTS_DIR/bin/escript $BINDIR/brod_cli "$@"
else
  # hoping the user has erts in PATH
  exec $BINDIR/brod_cli "$@"
fi

