#!/bin/sh

set -eu

THIS="$0"
CUR_DIR="$(pwd)"

# resolve the dir (maybe sym-linked) in which THIS script resides
cd "$(dirname "$THIS")"
TARGET_FILE="$(basename "$THIS")"
# use a while loop because readlink -f does not always work in all systems
while [ -L "$TARGET_FILE" ]; do
    TARGET_FILE="$(readlink "$TARGET_FILE")"
    cd "$(dirname "$TARGET_FILE")"
    TARGET_FILE="$(basename "$TARGET_FILE")"
done
BINDIR="$(pwd -P)"

# go back to the original PWD
cd "$CUR_DIR"

if [ -x  "$BINDIR/brod-i" ]; then
  # this is a release, try to use erts in release
  # brod-i find erts bin dir for us
  exec "$BINDIR/brod-i" escript bin/brod.escript "$@"
else
  # this is not a release, so we assume:
  # 1. the user has erts in PATH
  # 2. nif binary files are located in the bin dir
  export NIF_BIN_DIR=$BINDIR
  exec "$BINDIR/brod_cli" "$@"
fi
